### ISSUE TITLE
bower errors

### ISSUE THREAD

**Issue by nschloe** [Khan/KaTeX#181]
Installing KaTeX 0.1.1 yields
```
bower katex#*             invalid-meta katex is missing "main" entry in bower.json
bower katex#*             invalid-meta katex is missing "ignore" entry in bower.json
```

**Comment by shime** [comment]
:+1:

**Comment by shybovycha** [comment]
:+1:

**Comment by kevinb7** [comment]
I believe this issue has been fixed by https://github.com/Khan/KaTeX/commit/2060ebaf214739cda866368175185c5151b86426.  Let me know if that's not the case.

**Comment by franciscop** [comment]
Not fixed yet, I just received this error. From [this stackoverflow question](http://stackoverflow.com/q/29046960/938236), it looks like you might need to bump the version number. If I remember correctly, even if you update your code within a version (like happened here I think), bower will only get the original one. Maybe bump at patch level?

**Comment by kevinb7** [comment]
TBH, I didn't look carefully at the bower.json file before closing this.  I did try it out and didn't see any errors/warnings.  Not sure why my version of bower isn't reporting them.

**Comment by kevinb7** [comment]
@franciscop what version of bower are you running.  I'm going to add "main", but for the life of me I can't reproduce the error that you're seeing.

**Comment by kevinb7** [comment]
@franciscop It should be fixed with https://github.com/Khan/KaTeX/commit/4ea7d38b5c8eeb25c86ebb4f8b12b8be78aaf8fb.  Can you give it another try?

**Comment by franciscop** [comment]
Perfect :thumbsup:, tried again after deleting the repository and clean bower's cache and couldn't reproduce:

![cache clean](https://cloud.githubusercontent.com/assets/2801252/8270618/0489edc6-1823-11e5-8ed3-067f04de3279.png)
