### ISSUE TITLE
x'^2 throws exception

### ISSUE THREAD

**Issue by gagern** [Khan/KaTeX#634]
KaTeX refuses to render `x'^2` even though TeX does render this. It says

> KaTeX parse error: Double superscript at position 3: x'^̲2

[Here](https://github.com/Khan/KaTeX/blob/v0.7.0/src/Parser.js#L357-L358) is the code which treats pimes as superscripts. So apparently the font has something to do with is, since the symbol `\prime` seems to be styled such that it has to be in superscript style and position in order to work correctly.

LaTeX has the following lists for `$x'^2+x^\prime$`:

```tex
\mathord
.\fam1 x
^\mathord
^.\fam2 0
^\mathord
^.\fam0 2
\mathbin
.\fam0 +
\mathord
.\fam1 x
^\fam2 0
```

So I'd say handling this as a double superscript appears to be the correct way indeed, and we only have to get rid of the error message and do something reasonable for this input.

**Comment by edemaine** [comment]
Agreed.  It's curious because TeX *doesn't* support double superscripts (`$x^a^a$` is invalid), presumably so that ambiguities like `$x^a_a_b^b^c^d_d$` don't need to be resolved.  Also, `$x^a'$` produces a double-superscript error.

Ha, check out the definition of `'`: it checks via `\futurelet` whether the next symbol is `^`, and merges the superscripts in that case.  Also checks for following `'`s which KaTeX already does.

```latex
\def\active@math@prime{^\bgroup\prim@s}
{\catcode`\'=\active \global\let'\active@math@prime}
\def\prim@s{%
  \prime\futurelet\@let@token\pr@m@s}
\def\pr@m@s{%
  \ifx'\@let@token
    \expandafter\pr@@@s
  \else
    \ifx^\@let@token
      \expandafter\expandafter\expandafter\pr@@@t
    \else
      \egroup
    \fi
  \fi}
\def\pr@@@s#1{\prim@s}
\def\pr@@@t#1#2{#2\egroup}
```

So we just need to modify the prime handling in `Parser.js` to check for `^`s in `nextToken` as well.  Once we hit `^`, can call `handleSupSubscript`, and then prepend the `\prime`s to the superscript.

**Comment by edemaine** [comment]
Fixed in #636.

**Comment by gagern** [comment]
Fixed by #636. Thanks for the investigation!

**Comment by apowers313** [comment]
I downloaded the 0.7.1 release, which seems to be from two days after this issue was closed, but I'm still getting the problem reported here:

> KaTeX auto-render: Failed to parse `y'^2 = x'^3 + b'` with  Error: KaTeX parse error: Double superscript at position 3: y'^̲2 = x'^3 + b'

Should this be fixed in 0.7.1?

**Comment by edemaine** [comment]
I'm afraid not -- I'm pretty sure that 0.7.1 is a tweak to 0.7.0 which predates PR #636.  It will be in the next release...

**Comment by apowers313** [comment]
Thanks, it looks like cutting and pasting [these lines](https://github.com/edemaine/KaTeX/blob/b48c4c813295b90f133803b21834e5559dd6eec8/src/Parser.js#L360-L364) into the un-minified release seems to fix the problem. I'll roll with that until there's a new release.

Thanks again for the help.
