### ISSUE TITLE
\sqrt doesn't scale properly when browser is zoomed in or out on Safari

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/KaTeX#883]
`\sqrt{\frac{1}{x}}` produces the following output when zoom in:
<img width="261" alt="screen shot 2017-09-15 at 12 07 12 am" src="https://user-images.githubusercontent.com/1044413/30466220-53afcbf4-99aa-11e7-9c85-ddae5dc31db7.png">
and out:
<img width="89" alt="screen shot 2017-09-15 at 12 07 18 am" src="https://user-images.githubusercontent.com/1044413/30466217-4ec1cd90-99aa-11e7-897e-efea30db24c9.png">

**Comment by kevinbarabash** [comment]
It works fine in Chrome and Firefox.

**Comment by ronkok** [comment]
I'll look into it.

**Comment by ronkok** [comment]
It seems to be a problem with all the nested SVGs. The non-nested SVGs (`\cancel`, `widehat`, etc) seem to be working okay.  But in nested SVGs, the inner SVG is scaling taller than the outer SVG. The bottom of each one is being cut off and what can be seen is too large. I'll keep looking and report as I learn more.

**Comment by ronkok** [comment]
I think it probably is possible to re-write all the nested SVGs and instead use two or three single-level SVGs placed side by side. The variable-length arrow shafts will require CSS `calc(...)` if this scheme is to work. 

During very early drafts of PR #670, I tried this approach and had it working, sort of. I ended up using nested SVGs because I was getting better quality images. Maybe the side-by-side, CSS-controlled approach can succeed if I work it a little smarter.

This will take time. I'll make a progress report in a couple of days. I sure wish that Safari was better.

**Comment by kevinbarabash** [comment]
I'll try this out in the nightly webkit build and see if there's any info on the status of this bug anywhere.  If the bug's being fixed in Safari, no need to rework things.

**Comment by ronkok** [comment]
@kevinbarabash PR #890 fixes `sqrt` and single-ended arrows, but it does not fix double-ended arrows or horizontal braces. It may be a couple of weeks before I can address them.

**Comment by kevinbarabash** [comment]
@ronkok sounds good.  We can close this issue when #980 is merged and open another issue just for double-ended arrow and horizontal braces.

**Comment by ronkok** [comment]
I believe that this issue is now resolved.
